/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class java_net_InetAddressImpl */

#ifndef _Included_java_net_InetAddressImpl
#define _Included_java_net_InetAddressImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     java_net_InetAddressImpl
 * Method:    getLocalHostName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_java_net_InetAddressImpl_getLocalHostName
  (JNIEnv *, jobject);

/*
 * Class:     java_net_InetAddressImpl
 * Method:    makeAnyLocalAddress
 * Signature: (Ljava/net/InetAddress;)V
 */
JNIEXPORT void JNICALL Java_java_net_InetAddressImpl_makeAnyLocalAddress
  (JNIEnv *, jobject, jobject);

/*
 * Class:     java_net_InetAddressImpl
 * Method:    lookupAllHostAddr
 * Signature: (Ljava/lang/String;)[[B
 */
JNIEXPORT jobjectArray JNICALL Java_java_net_InetAddressImpl_lookupAllHostAddr
  (JNIEnv *, jobject, jstring);

/*
 * Class:     java_net_InetAddressImpl
 * Method:    getHostByAddr
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_java_net_InetAddressImpl_getHostByAddr
  (JNIEnv *, jobject, jint);

/*
 * Class:     java_net_InetAddressImpl
 * Method:    getInetFamily
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_java_net_InetAddressImpl_getInetFamily
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
