/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class gnu_vm_stack_StackFrame */

#ifndef _Included_gnu_vm_stack_StackFrame
#define _Included_gnu_vm_stack_StackFrame
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
