/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class java_io_VMObjectStreamClass */

#ifndef _Included_java_io_VMObjectStreamClass
#define _Included_java_io_VMObjectStreamClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     java_io_VMObjectStreamClass
 * Method:    hasClassInitializer
 * Signature: (Ljava/lang/Class;)Z
 */
JNIEXPORT jboolean JNICALL Java_java_io_VMObjectStreamClass_hasClassInitializer
  (JNIEnv *, jclass, jclass);

#ifdef __cplusplus
}
#endif
#endif
