/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class VideoCapture */

#ifndef _Included_VideoCapture
#define _Included_VideoCapture
#ifdef __cplusplus
extern "C" {
#endif
#undef VideoCapture_VIDEO_MODE_PAL
#define VideoCapture_VIDEO_MODE_PAL 0L
#undef VideoCapture_VIDEO_MODE_NTSC
#define VideoCapture_VIDEO_MODE_NTSC 1L
#undef VideoCapture_VIDEO_MODE_SECAM
#define VideoCapture_VIDEO_MODE_SECAM 2L
#undef VideoCapture_VIDEO_MODE_AUTO
#define VideoCapture_VIDEO_MODE_AUTO 3L
#undef VideoCapture_VIDEO_PALETTE_GREY
#define VideoCapture_VIDEO_PALETTE_GREY 1L
#undef VideoCapture_VIDEO_PALETTE_HI240
#define VideoCapture_VIDEO_PALETTE_HI240 2L
#undef VideoCapture_VIDEO_PALETTE_RGB565
#define VideoCapture_VIDEO_PALETTE_RGB565 3L
#undef VideoCapture_VIDEO_PALETTE_RGB24
#define VideoCapture_VIDEO_PALETTE_RGB24 4L
#undef VideoCapture_VIDEO_PALETTE_RGB32
#define VideoCapture_VIDEO_PALETTE_RGB32 5L
#undef VideoCapture_VIDEO_PALETTE_RGB555
#define VideoCapture_VIDEO_PALETTE_RGB555 6L
#undef VideoCapture_VIDEO_PALETTE_YUV422
#define VideoCapture_VIDEO_PALETTE_YUV422 7L
#undef VideoCapture_VIDEO_PALETTE_YUYV
#define VideoCapture_VIDEO_PALETTE_YUYV 8L
#undef VideoCapture_VIDEO_PALETTE_UYVY
#define VideoCapture_VIDEO_PALETTE_UYVY 9L
#undef VideoCapture_VIDEO_PALETTE_YUV420
#define VideoCapture_VIDEO_PALETTE_YUV420 10L
#undef VideoCapture_VIDEO_PALETTE_YUV411
#define VideoCapture_VIDEO_PALETTE_YUV411 11L
#undef VideoCapture_VIDEO_PALETTE_RAW
#define VideoCapture_VIDEO_PALETTE_RAW 12L
#undef VideoCapture_VIDEO_PALETTE_YUV422P
#define VideoCapture_VIDEO_PALETTE_YUV422P 13L
#undef VideoCapture_VIDEO_PALETTE_YUV411P
#define VideoCapture_VIDEO_PALETTE_YUV411P 14L
#undef VideoCapture_VIDEO_PALETTE_YUV420P
#define VideoCapture_VIDEO_PALETTE_YUV420P 15L
#undef VideoCapture_VIDEO_PALETTE_YUV410P
#define VideoCapture_VIDEO_PALETTE_YUV410P 16L
#undef VideoCapture_VIDEO_PALETTE_PLANAR
#define VideoCapture_VIDEO_PALETTE_PLANAR 13L
#undef VideoCapture_VIDEO_PALETTE_COMPONENT
#define VideoCapture_VIDEO_PALETTE_COMPONENT 7L
/*
 * Class:     VideoCapture
 * Method:    capture
 * Signature: (I[I)V
 */
JNIEXPORT void JNICALL Java_VideoCapture_capture__I_3I
  (JNIEnv *, jobject, jint, jintArray);

/*
 * Class:     VideoCapture
 * Method:    capture
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_VideoCapture_capture___3B
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     VideoCapture
 * Method:    capture
 * Signature: ([I)V
 */
JNIEXPORT void JNICALL Java_VideoCapture_capture___3I
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     VideoCapture
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_VideoCapture_close
  (JNIEnv *, jobject);

/*
 * Class:     VideoCapture
 * Method:    open
 * Signature: (Ljava/lang/String;IIIIIIIII)V
 */
JNIEXPORT void JNICALL Java_VideoCapture_open
  (JNIEnv *, jobject, jstring, jint, jint, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     VideoCapture
 * Method:    selectChannel
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_VideoCapture_selectChannel
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     VideoCapture
 * Method:    setCapSize
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_VideoCapture_setCapSize
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     VideoCapture
 * Method:    setColors
 * Signature: (IIIIIII)V
 */
JNIEXPORT void JNICALL Java_VideoCapture_setColors
  (JNIEnv *, jobject, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     VideoCapture
 * Method:    showInfo
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_VideoCapture_showInfo
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
