#!/bin/bash

echo "Compiling everything in $1"

export CLASSPATH=$CLASSPATH:`pwd`

cd $1 && \
rm -f *.class && \
rm -f *~ && \
for file in *.java; do \
    echo -n "  Compiling $file ..."; \
    javac -classpath $CLASSPATH $file; \
    echo done; \
done;

