#!/bin/bash

echo "TODO: Write a more elegant version of me!"

export CLASSPATH=$HOME/Harpoon/Code/SupportNP/classes.zip:$CLASSPATH

# Building the RealTime Java benchmarks
OLD_CLASSPATH=$CLASSPATH

export CLASSPATH=/home/salcianu/Harpoon/Code/Support/realtime.jar:$CLASSPATH

#./buildone FibPaper

#./buildone Water/Water_RTJ/CTMemory
#./buildone Water/Water_RTJ/VTMemory

#./buildone Barnes/Barnes_RTJ/CTMemory
#./buildone Barnes/Barnes_RTJ/VTMemory

#./buildone HTTP/HTTP_RTJ/CTMemory
#./buildone HTTP/HTTP_RTJ/VTMemory

#./buildone Quote/Quote_RTJ

#./buildone Toy_RTJ

export CLASSPATH=${OLD_CLASSPATH}

./buildone ETruc

./buildone db

./buildone Barnes/Barnes

./buildone Water/Water

./buildone Chat/Chat
./buildone Chat/Client

./buildone Echo/Echo

./buildone Game/Game
./buildone Game/Client

./buildone HTTP/HTTP

echo -n "Compiling the HTTP C client ..."
gcc -o HTTP/Client/webmark2 HTTP/Client/webmark2.c
echo done

./buildone Phone/Phone
echo -n "Compiling the Phone C client ..."
gcc -o Phone/Client/phonemark Phone/Client/phonemark.c
echo done

./buildone Quote/Quote
./buildone Quote/Client

./buildone Time/Time
echo -n "Compiling the Time C client ..."
gcc -o Time/Client/timemark Time/Client/timemark.c
echo done

./buildone martin-raytrace
