#!/bin/sh
# configure runtime for cross-compilation.
# usage:
#   ./configure-cross-compiler [host-name] [configure options]
# the 'host-name' parameter will be something like 'arm-unknown-linuxelf'

set -e 

# src and h2t should be inverses.
src=.
h2t=.
# where to find config.guess
cgloc=/usr/share/automake

instdir=/usr
buildroot=/home/flex/SKIFFROOT/shared

makeopt= # -d

target=$1 # arm-unknown-linuxelf
shift
action=#install

build=`$cgloc/config.guess` 
host="$target"

# Both configure and make need to be told where to find the various pieces. 
# Define several variables of the things we need to pass to configure and make. 

# These are for building programs that run on $build. 
CC_FOR_BUILD=gcc 
CXX_FOR_BUILD=gcc 

# These are for building programs and libraries that run on $host. 
CC=$host-gcc 
AR=$host-ar 
AS=$host-as
NM=$host-nm
RANLIB=$host-ranlib 

# These are for building libraries that run on $target. 
CC_FOR_TARGET="$CC"
GCC_FOR_TARGET="$CC_FOR_TARGET" 
CC_FOR_TARGET="$CC_FOR_TARGET" 
CXX_FOR_TARGET="$CC_FOR_TARGET" 
AS_FOR_TARGET=$host-gcc
LD_FOR_TARGET=$host-ld
NM_FOR_TARGET=$host-nm
AR_FOR_TARGET=$host-ar 
RANLIB_FOR_TARGET=$host-ranlib 

CC="$CC" AR="$AR" AS="$AS" RANLIB="$RANLIB" NM="$NM" HOSTCC="$CC_FOR_BUILD" $src/configure --build=${build} --host=${host} --target=${target} --prefix=$instdir --with-gnu-ld --with-gnu-as $*

exit $?
