# additional rules for making java archives.
# define $(JAVASRC) before including this.

EXTRA_DIST:=$(EXTRA_DIST) $(JAVASRC)
CLEANFILES:=$(CLEANFILES) $(JARFILE)
if BUILD_JAVA_SOURCE
noinst_DATA=$(JARFILE)
endif

classes: $(JAVASRC)
	-$(RM) -rf $@
	$(JAVAC) -d $@ -g $^
$(JARFILE): classes
	$(JAR) -cf $@ -C classes .
mostlyclean clean: clean-classes
clean-classes:
	-$(RM) -rf classes

# a more precise rule might look like this:
# (ideally JAVAPKG would be generated by a shell script from the input file)

# JAVACLS=$(foreach f,$(JAVASRC:.java=.class),classes/$(JAVAPKG)/$(f))
# $(JAVACLS): $(JAVASRC)
# 	jikes-classpath -d classes -g $^
# $(JARFILE): $(JAVACLS)
# 	jar -cf $@ -C classes .
