#!/bin/sh
#  build the automake/autoconf magic needed to build the rest of the runtime.
test -f include/stamp-h.in || touch include/stamp-h.in
libtoolize --automake
aclocal
autoheader
automake --add-missing
autoconf
set +x
if test -f config.status; then
    sh config.status
fi
