/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class java_lang_reflect_AccessibleObject */

#ifndef _Included_java_lang_reflect_AccessibleObject
#define _Included_java_lang_reflect_AccessibleObject
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: class_00024Ljava_00024lang_00024Class */
/* Inaccessible static: class_00024Ljava_00024lang_00024reflect_00024AccessibleObject */
#ifdef __cplusplus
}
#endif
#endif
