/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class java_lang_reflect_Field */

#ifndef _Included_java_lang_reflect_Field
#define _Included_java_lang_reflect_Field
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: class_00024java_00024lang_00024Class */
/* Inaccessible static: class_00024java_00024lang_00024reflect_00024AccessibleObject */
/*
 * Class:     java_lang_reflect_Field
 * Method:    getDeclaringClass
 * Signature: ()Ljava/lang/Class;
 */
JNIEXPORT jclass JNICALL Java_java_lang_reflect_Field_getDeclaringClass
  (JNIEnv *, jobject);

/*
 * Class:     java_lang_reflect_Field
 * Method:    getName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_java_lang_reflect_Field_getName
  (JNIEnv *, jobject);

/*
 * Class:     java_lang_reflect_Field
 * Method:    getModifiers
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_java_lang_reflect_Field_getModifiers
  (JNIEnv *, jobject);

/*
 * Class:     java_lang_reflect_Field
 * Method:    getType
 * Signature: ()Ljava/lang/Class;
 */
JNIEXPORT jclass JNICALL Java_java_lang_reflect_Field_getType
  (JNIEnv *, jobject);

/*
 * Class:     java_lang_reflect_Field
 * Method:    get
 * Signature: (Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_java_lang_reflect_Field_get
  (JNIEnv *, jobject, jobject);

/*
 * Class:     java_lang_reflect_Field
 * Method:    set
 * Signature: (Ljava/lang/Object;Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_java_lang_reflect_Field_set
  (JNIEnv *, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
