/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class java_lang_reflect_Member */

#ifndef _Included_java_lang_reflect_Member
#define _Included_java_lang_reflect_Member
#ifdef __cplusplus
extern "C" {
#endif
#undef java_lang_reflect_Member_DECLARED
#define java_lang_reflect_Member_DECLARED 1L
#undef java_lang_reflect_Member_PUBLIC
#define java_lang_reflect_Member_PUBLIC 0L
#ifdef __cplusplus
}
#endif
#endif
