/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class java_lang_reflect_Modifier */

#ifndef _Included_java_lang_reflect_Modifier
#define _Included_java_lang_reflect_Modifier
#ifdef __cplusplus
extern "C" {
#endif
#undef java_lang_reflect_Modifier_PUBLIC
#define java_lang_reflect_Modifier_PUBLIC 1L
#undef java_lang_reflect_Modifier_PRIVATE
#define java_lang_reflect_Modifier_PRIVATE 2L
#undef java_lang_reflect_Modifier_PROTECTED
#define java_lang_reflect_Modifier_PROTECTED 4L
#undef java_lang_reflect_Modifier_STATIC
#define java_lang_reflect_Modifier_STATIC 8L
#undef java_lang_reflect_Modifier_FINAL
#define java_lang_reflect_Modifier_FINAL 16L
#undef java_lang_reflect_Modifier_SYNCHRONIZED
#define java_lang_reflect_Modifier_SYNCHRONIZED 32L
#undef java_lang_reflect_Modifier_VOLATILE
#define java_lang_reflect_Modifier_VOLATILE 64L
#undef java_lang_reflect_Modifier_TRANSIENT
#define java_lang_reflect_Modifier_TRANSIENT 128L
#undef java_lang_reflect_Modifier_NATIVE
#define java_lang_reflect_Modifier_NATIVE 256L
#undef java_lang_reflect_Modifier_INTERFACE
#define java_lang_reflect_Modifier_INTERFACE 512L
#undef java_lang_reflect_Modifier_ABSTRACT
#define java_lang_reflect_Modifier_ABSTRACT 1024L
#undef java_lang_reflect_Modifier_STRICT
#define java_lang_reflect_Modifier_STRICT 2048L
#undef java_lang_reflect_Modifier_SUPER
#define java_lang_reflect_Modifier_SUPER 32L
#undef java_lang_reflect_Modifier_ALL_FLAGS
#define java_lang_reflect_Modifier_ALL_FLAGS 4095L
#ifdef __cplusplus
}
#endif
#endif
