/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class harpoon_Runtime_PreciseGC_WriteBarrier */

#ifndef _Included_harpoon_Runtime_PreciseGC_WriteBarrier
#define _Included_harpoon_Runtime_PreciseGC_WriteBarrier
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     harpoon_Runtime_PreciseGC_WriteBarrier
 * Method:    storeCheck
 * Signature: (Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_harpoon_Runtime_PreciseGC_WriteBarrier_storeCheck
  (JNIEnv *, jclass, jobject);

/*
 * Class:     harpoon_Runtime_PreciseGC_WriteBarrier
 * Method:    fsc
 * Signature: (Ljava/lang/Object;Ljava/lang/reflect/Field;Ljava/lang/Object;I)V
 */
JNIEXPORT void JNICALL Java_harpoon_Runtime_PreciseGC_WriteBarrier_fsc
  (JNIEnv *, jclass, jobject, jobject, jobject, jint);

/*
 * Class:     harpoon_Runtime_PreciseGC_WriteBarrier
 * Method:    rfsc
 * Signature: (Ljava/lang/Object;Ljava/lang/reflect/Field;Ljava/lang/Object;I)V
 */
JNIEXPORT void JNICALL Java_harpoon_Runtime_PreciseGC_WriteBarrier_rfsc
  (JNIEnv *, jclass, jobject, jobject, jobject, jint);

/*
 * Class:     harpoon_Runtime_PreciseGC_WriteBarrier
 * Method:    asc
 * Signature: (Ljava/lang/Object;ILjava/lang/Object;I)V
 */
JNIEXPORT void JNICALL Java_harpoon_Runtime_PreciseGC_WriteBarrier_asc
  (JNIEnv *, jclass, jobject, jint, jobject, jint);

/*
 * Class:     harpoon_Runtime_PreciseGC_WriteBarrier
 * Method:    rasc
 * Signature: (Ljava/lang/Object;ILjava/lang/Object;I)V
 */
JNIEXPORT void JNICALL Java_harpoon_Runtime_PreciseGC_WriteBarrier_rasc
  (JNIEnv *, jclass, jobject, jint, jobject, jint);

/*
 * Class:     harpoon_Runtime_PreciseGC_WriteBarrier
 * Method:    clearBit
 * Signature: (Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_harpoon_Runtime_PreciseGC_WriteBarrier_clearBit
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
