/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class java_lang_Double */

#ifndef _Included_java_lang_Double
#define _Included_java_lang_Double
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     java_lang_Double
 * Method:    doubleToLongBits
 * Signature: (D)J
 */
JNIEXPORT jlong JNICALL Java_java_lang_Double_doubleToLongBits
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     java_lang_Double
 * Method:    longBitsToDouble
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_java_lang_Double_longBitsToDouble
  (JNIEnv *, jclass, jlong);

/*
 * Class:     java_lang_Double
 * Method:    valueOf0
 * Signature: (Ljava/lang/String;)D
 */
JNIEXPORT jdouble JNICALL Java_java_lang_Double_valueOf0
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
