// HoughPoly.java, created by wbeebee
// Copyright (C) 2003 Wes Beebee <wbeebee@mit.edu>
// Licensed under the terms of the GNU GPL; see COPYING for details.
package imagerec.graph;

/**
 * A {@link HoughPoly} node can take a thinned <code>r vs. t</code>
 * graph, generated by {@link HoughThin} and generate a list
 * of polygons from it.
 *
 * @see Hough DeHoughPoly
 *
 * @author Wes Beebee <<a href="mailto:wbeebee@mit.edu">wbeebee@mit.edu</a>>
 */
public class HoughPoly extends Node {
    private final String filePrefix;
    private final boolean intensity, inorder;

    /** Construct a {@link HoughPoly} which will take a <code>r vs. t</code>
     *  graph and construct a list of lines from it.
     *
     *  @param filePrefix The prefix of the name of the files to save the 
     *                    list of lines in.  The file names will be 
     *                    <code>filePrefix.#</code>.
     *  @param intensity Whether to store intensities (degree of certainty) 
     *                   of lines in the file.
     *  @param inorder Whether to use the <code>id</code> or count images
     *                 coming in.
     */
    public HoughPoly(String filePrefix, boolean intensity, boolean inorder) {
	super();
	this.filePrefix = filePrefix;
	this.intensity = intensity;
	this.inorder = inorder;
    }

    /** <code>process</code> an <code>r vs. t</code> graph by
     *  listing the lines (which can form polygons) in it.
     */
    public synchronized void process(ImageData id) {
	

	super.process(id);
    }

}
