/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class IPaqServoController */

#ifndef _Included_IPaqServoController
#define _Included_IPaqServoController
#ifdef __cplusplus
extern "C" {
#endif
#undef IPaqServoController_SERVER_PORT
#define IPaqServoController_SERVER_PORT 17010L
#undef IPaqServoController_MAX_CLIENTS
#define IPaqServoController_MAX_CLIENTS 50L
/*
 * Class:     IPaqServoController
 * Method:    setup
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_IPaqServoController_setup
  (JNIEnv *, jclass);

/*
 * Class:     IPaqServoController
 * Method:    sendSerial
 * Signature: (B)V
 */
JNIEXPORT void JNICALL Java_IPaqServoController_sendSerial
  (JNIEnv *, jclass, jbyte);

/*
 * Class:     IPaqServoController
 * Method:    readSerial
 * Signature: ()B
 */
JNIEXPORT jbyte JNICALL Java_IPaqServoController_readSerial
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
