/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class java_lang_Throwable */

#ifndef _Included_java_lang_Throwable
#define _Included_java_lang_Throwable
#ifdef __cplusplus
extern "C" {
#endif
#undef java_lang_Throwable_serialVersionUID
#define java_lang_Throwable_serialVersionUID -3042686055658047285LL
/*
 * Class:     java_lang_Throwable
 * Method:    printStackTrace0
 * Signature: (Ljava/io/PrintWriter;)V
 */
JNIEXPORT void JNICALL Java_java_lang_Throwable_printStackTrace0
  (JNIEnv *, jobject, jobject);

/*
 * Class:     java_lang_Throwable
 * Method:    fillInStackTrace
 * Signature: ()Ljava/lang/Throwable;
 */
JNIEXPORT jthrowable JNICALL Java_java_lang_Throwable_fillInStackTrace
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
