/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class java_lang_VMSecurityManager */

#ifndef _Included_java_lang_VMSecurityManager
#define _Included_java_lang_VMSecurityManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     java_lang_VMSecurityManager
 * Method:    getClassContext
 * Signature: ()[Ljava/lang/Class;
 */
JNIEXPORT jobjectArray JNICALL Java_java_lang_VMSecurityManager_getClassContext
  (JNIEnv *, jclass);

/*
 * Class:     java_lang_VMSecurityManager
 * Method:    currentClassLoader
 * Signature: ()Ljava/lang/ClassLoader;
 */
JNIEXPORT jobject JNICALL Java_java_lang_VMSecurityManager_currentClassLoader
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
