/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class java_lang_VMClassLoader */

#ifndef _Included_java_lang_VMClassLoader
#define _Included_java_lang_VMClassLoader
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: class_00024java_00024lang_00024ClassLoader */
/*
 * Class:     java_lang_VMClassLoader
 * Method:    defineClass
 * Signature: (Ljava/lang/ClassLoader;Ljava/lang/String;[BIILjava/security/ProtectionDomain;)Ljava/lang/Class;
 */
JNIEXPORT jclass JNICALL Java_java_lang_VMClassLoader_defineClass
  (JNIEnv *, jclass, jobject, jstring, jbyteArray, jint, jint, jobject);

/*
 * Class:     java_lang_VMClassLoader
 * Method:    resolveClass
 * Signature: (Ljava/lang/Class;)V
 */
JNIEXPORT void JNICALL Java_java_lang_VMClassLoader_resolveClass
  (JNIEnv *, jclass, jclass);

/*
 * Class:     java_lang_VMClassLoader
 * Method:    loadClass
 * Signature: (Ljava/lang/String;Z)Ljava/lang/Class;
 */
JNIEXPORT jclass JNICALL Java_java_lang_VMClassLoader_loadClass
  (JNIEnv *, jclass, jstring, jboolean);

/*
 * Class:     java_lang_VMClassLoader
 * Method:    getPrimitiveClass
 * Signature: (Ljava/lang/String;)Ljava/lang/Class;
 */
JNIEXPORT jclass JNICALL Java_java_lang_VMClassLoader_getPrimitiveClass
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
