/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class java_lang_VMSecurityManager */

#ifndef _Included_java_lang_VMSecurityManager
#define _Included_java_lang_VMSecurityManager
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
