/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class java_lang_Console */

#ifndef _Included_java_lang_Console
#define _Included_java_lang_Console
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     java_lang_Console
 * Method:    print
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_java_lang_Console_print
  (JNIEnv *, jclass, jstring);

/*
 * Class:     java_lang_Console
 * Method:    println
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_java_lang_Console_println
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
