/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class java_lang_Throwable */

#ifndef _Included_java_lang_Throwable
#define _Included_java_lang_Throwable
#ifdef __cplusplus
extern "C" {
#endif
#undef java_lang_Throwable_serialVersionUID
#define java_lang_Throwable_serialVersionUID -3042686055658047285LL
#ifdef __cplusplus
}
#endif
#endif
