/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class edu_uci_ece_ac_time_HighResClock */

#ifndef _Included_edu_uci_ece_ac_time_HighResClock
#define _Included_edu_uci_ece_ac_time_HighResClock
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_uci_ece_ac_time_HighResClock
 * Method:    getTime
 * Signature: (Ledu/uci/ece/ac/time/HighResTime;)V
 */
JNIEXPORT void JNICALL Java_edu_uci_ece_ac_time_HighResClock_getTime
  (JNIEnv *, jclass, jobject);

/*
 * Class:     edu_uci_ece_ac_time_HighResClock
 * Method:    getClockTickCount
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_edu_uci_ece_ac_time_HighResClock_getClockTickCount
  (JNIEnv *, jclass);

/*
 * Class:     edu_uci_ece_ac_time_HighResClock
 * Method:    clockTick2HighResTime
 * Signature: (JLedu/uci/ece/ac/time/HighResTime;)V
 */
JNIEXPORT void JNICALL Java_edu_uci_ece_ac_time_HighResClock_clockTick2HighResTime
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     edu_uci_ece_ac_time_HighResClock
 * Method:    getClockFrequency
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_edu_uci_ece_ac_time_HighResClock_getClockFrequency
  (JNIEnv *, jclass);

/*
 * Class:     edu_uci_ece_ac_time_HighResClock
 * Method:    getClockPeriod
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_edu_uci_ece_ac_time_HighResClock_getClockPeriod
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
