/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class harpoon_Runtime_Transactions_CommitRecord */

#ifndef _Included_harpoon_Runtime_Transactions_CommitRecord
#define _Included_harpoon_Runtime_Transactions_CommitRecord
#ifdef __cplusplus
extern "C" {
#endif
#undef harpoon_Runtime_Transactions_CommitRecord_WAITING
#define harpoon_Runtime_Transactions_CommitRecord_WAITING 0L
#undef harpoon_Runtime_Transactions_CommitRecord_COMMITTED
#define harpoon_Runtime_Transactions_CommitRecord_COMMITTED 1L
#undef harpoon_Runtime_Transactions_CommitRecord_ABORTED
#define harpoon_Runtime_Transactions_CommitRecord_ABORTED 2L
/*
 * Class:     harpoon_Runtime_Transactions_CommitRecord
 * Method:    state
 * Signature: (Lharpoon/Runtime/Transactions/CommitRecord;)I
 */
JNIEXPORT jint JNICALL Java_harpoon_Runtime_Transactions_CommitRecord_state
  (JNIEnv *, jclass, jobject);

/*
 * Class:     harpoon_Runtime_Transactions_CommitRecord
 * Method:    abort
 * Signature: (Lharpoon/Runtime/Transactions/CommitRecord;)I
 */
JNIEXPORT jint JNICALL Java_harpoon_Runtime_Transactions_CommitRecord_abort
  (JNIEnv *, jclass, jobject);

/*
 * Class:     harpoon_Runtime_Transactions_CommitRecord
 * Method:    commit
 * Signature: (Lharpoon/Runtime/Transactions/CommitRecord;)I
 */
JNIEXPORT jint JNICALL Java_harpoon_Runtime_Transactions_CommitRecord_commit
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
