/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class harpoon_Runtime_Transactions_ImplHelper */

#ifndef _Included_harpoon_Runtime_Transactions_ImplHelper
#define _Included_harpoon_Runtime_Transactions_ImplHelper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     harpoon_Runtime_Transactions_ImplHelper
 * Method:    setJNITransaction
 * Signature: (Lharpoon/Runtime/Transactions/CommitRecord;)Lharpoon/Runtime/Transactions/CommitRecord;
 */
JNIEXPORT jobject JNICALL Java_harpoon_Runtime_Transactions_ImplHelper_setJNITransaction
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
