/* DO NOT EDIT THIS FILE - it is machine generated */

#ifndef __java_io_FileOutputStream__
#define __java_io_FileOutputStream__

#include <jni.h>

#ifdef __cplusplus
extern "C"
{
#endif

extern void Java_java_io_FileOutputStream_writeInternal (JNIEnv *env, jobject obj, jint native_fd, jbyteArray buf, jint offset, jint len);
extern jint Java_java_io_FileOutputStream_open (JNIEnv *env, jobject obj, jstring name, jboolean append);
extern void Java_java_io_FileOutputStream_closeInternal (JNIEnv *env, jobject obj, jint native_fd);

extern void Java_java_io_FileOutputStream_writeInternal_00024_00024withtrans (JNIEnv *env, jobject obj, jobject commitrec, jint native_fd, jbyteArray buf, jint offset, jint len);
extern jint Java_java_io_FileOutputStream_open_00024_00024withtrans (JNIEnv *env, jobject obj, jobject commitrec, jstring name, jboolean append);
extern void Java_java_io_FileOutputStream_closeInternal_00024_00024withtrans (JNIEnv *env, jobject obj, jobject commitrec, jint native_fd);

#ifdef __cplusplus
}
#endif

#endif /* __java_io_FileOutputStream__ */
