/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class AltVideo */

#ifndef _Included_AltVideo
#define _Included_AltVideo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     AltVideo
 * Method:    capture
 * Signature: (II[I)Z
 */
JNIEXPORT jboolean JNICALL Java_AltVideo_capture
  (JNIEnv *, jclass, jint, jint, jintArray);

#ifdef __cplusplus
}
#endif
#endif
