/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class java_io_ObjectStreamClass */

#ifndef _Included_java_io_ObjectStreamClass
#define _Included_java_io_ObjectStreamClass
#ifdef __cplusplus
extern "C" {
#endif
#undef java_io_ObjectStreamClass_serialVersionUID
#define java_io_ObjectStreamClass_serialVersionUID -6120832682080437368LL
#undef java_io_ObjectStreamClass_M_TRANSIENT
#define java_io_ObjectStreamClass_M_TRANSIENT 128L
#undef java_io_ObjectStreamClass_M_PRIVATE
#define java_io_ObjectStreamClass_M_PRIVATE 2L
#undef java_io_ObjectStreamClass_M_STATIC
#define java_io_ObjectStreamClass_M_STATIC 8L
/* Inaccessible static: descriptorFor */
/* Inaccessible static: classSerializable */
/* Inaccessible static: classExternalizable */
/*
 * Class:     java_io_ObjectStreamClass
 * Method:    getClassAccess
 * Signature: (Ljava/lang/Class;)I
 */
JNIEXPORT jint JNICALL Java_java_io_ObjectStreamClass_getClassAccess
  (JNIEnv *, jclass, jclass);

/*
 * Class:     java_io_ObjectStreamClass
 * Method:    getMethodSignatures
 * Signature: (Ljava/lang/Class;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_java_io_ObjectStreamClass_getMethodSignatures
  (JNIEnv *, jclass, jclass);

/*
 * Class:     java_io_ObjectStreamClass
 * Method:    getMethodAccess
 * Signature: (Ljava/lang/Class;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_java_io_ObjectStreamClass_getMethodAccess
  (JNIEnv *, jclass, jclass, jstring);

/*
 * Class:     java_io_ObjectStreamClass
 * Method:    getFieldSignatures
 * Signature: (Ljava/lang/Class;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_java_io_ObjectStreamClass_getFieldSignatures
  (JNIEnv *, jclass, jclass);

/*
 * Class:     java_io_ObjectStreamClass
 * Method:    getFieldAccess
 * Signature: (Ljava/lang/Class;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_java_io_ObjectStreamClass_getFieldAccess
  (JNIEnv *, jclass, jclass, jstring);

/*
 * Class:     java_io_ObjectStreamClass
 * Method:    getFields0
 * Signature: (Ljava/lang/Class;)[Ljava/io/ObjectStreamField;
 */
JNIEXPORT jobjectArray JNICALL Java_java_io_ObjectStreamClass_getFields0
  (JNIEnv *, jobject, jclass);

/*
 * Class:     java_io_ObjectStreamClass
 * Method:    getSerialVersionUID
 * Signature: (Ljava/lang/Class;)J
 */
JNIEXPORT jlong JNICALL Java_java_io_ObjectStreamClass_getSerialVersionUID
  (JNIEnv *, jclass, jclass);

/*
 * Class:     java_io_ObjectStreamClass
 * Method:    hasWriteObject
 * Signature: (Ljava/lang/Class;)Z
 */
JNIEXPORT jboolean JNICALL Java_java_io_ObjectStreamClass_hasWriteObject
  (JNIEnv *, jclass, jclass);

#ifdef __cplusplus
}
#endif
#endif
