/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class java_io_ObjectOutputStream */

#ifndef _Included_java_io_ObjectOutputStream
#define _Included_java_io_ObjectOutputStream
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     java_io_ObjectOutputStream
 * Method:    outputClassFields
 * Signature: (Ljava/lang/Object;Ljava/lang/Class;[I)V
 */
JNIEXPORT void JNICALL Java_java_io_ObjectOutputStream_outputClassFields
  (JNIEnv *, jobject, jobject, jclass, jintArray);

/*
 * Class:     java_io_ObjectOutputStream
 * Method:    invokeObjectWriter
 * Signature: (Ljava/lang/Object;Ljava/lang/Class;)Z
 */
JNIEXPORT jboolean JNICALL Java_java_io_ObjectOutputStream_invokeObjectWriter
  (JNIEnv *, jobject, jobject, jclass);

#ifdef __cplusplus
}
#endif
#endif
