/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class javax_realtime_ScopedMemory */

#ifndef _Included_javax_realtime_ScopedMemory
#define _Included_javax_realtime_ScopedMemory
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: num */
/* Inaccessible static: nullClassArr */
/* Inaccessible static: nullObjArr */
/* Inaccessible static: class_00024java_00024lang_00024Class */
/* Inaccessible static: class_00024java_00024lang_00024Object */
#undef javax_realtime_ScopedMemory_checkPortals
#define javax_realtime_ScopedMemory_checkPortals 0L
/*
 * Class:     javax_realtime_ScopedMemory
 * Method:    DECREF
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_javax_realtime_ScopedMemory_DECREF
  (JNIEnv *, jobject);

/*
 * Class:     javax_realtime_ScopedMemory
 * Method:    INCREF
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_javax_realtime_ScopedMemory_INCREF
  (JNIEnv *, jobject);

/*
 * Class:     javax_realtime_ScopedMemory
 * Method:    setPortalObj
 * Signature: (Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_javax_realtime_ScopedMemory_setPortalObj
  (JNIEnv *, jobject, jobject);

/*
 * Class:     javax_realtime_ScopedMemory
 * Method:    getPortalObj
 * Signature: ()Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_javax_realtime_ScopedMemory_getPortalObj
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
