/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class javax_realtime_SizeEstimator */

#ifndef _Included_javax_realtime_SizeEstimator
#define _Included_javax_realtime_SizeEstimator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     javax_realtime_SizeEstimator
 * Method:    objSize
 * Signature: (Ljava/lang/Class;)J
 */
JNIEXPORT jlong JNICALL Java_javax_realtime_SizeEstimator_objSize
  (JNIEnv *, jclass, jclass);

#ifdef __cplusplus
}
#endif
#endif
