/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class java_io_FileDescriptor */

#ifndef _Included_java_io_FileDescriptor
#define _Included_java_io_FileDescriptor
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: in */
/* Inaccessible static: out */
/* Inaccessible static: err */
/*
 * Class:     java_io_FileDescriptor
 * Method:    initIDs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_java_io_FileDescriptor_initIDs
  (JNIEnv *, jclass);

/*
 * Class:     java_io_FileDescriptor
 * Method:    sync
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_java_io_FileDescriptor_sync
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
