/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class java_io_RandomAccessFile */

#ifndef _Included_java_io_RandomAccessFile
#define _Included_java_io_RandomAccessFile
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     java_io_RandomAccessFile
 * Method:    open
 * Signature: (Ljava/lang/String;Z)V
 */
JNIEXPORT void JNICALL Java_java_io_RandomAccessFile_open
  (JNIEnv *, jobject, jstring, jboolean);

/*
 * Class:     java_io_RandomAccessFile
 * Method:    read
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_java_io_RandomAccessFile_read
  (JNIEnv *, jobject);

/*
 * Class:     java_io_RandomAccessFile
 * Method:    readBytes
 * Signature: ([BII)I
 */
JNIEXPORT jint JNICALL Java_java_io_RandomAccessFile_readBytes
  (JNIEnv *, jobject, jbyteArray, jint, jint);

/*
 * Class:     java_io_RandomAccessFile
 * Method:    write
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_java_io_RandomAccessFile_write
  (JNIEnv *, jobject, jint);

/*
 * Class:     java_io_RandomAccessFile
 * Method:    writeBytes
 * Signature: ([BII)V
 */
JNIEXPORT void JNICALL Java_java_io_RandomAccessFile_writeBytes
  (JNIEnv *, jobject, jbyteArray, jint, jint);

/*
 * Class:     java_io_RandomAccessFile
 * Method:    getFilePointer
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_java_io_RandomAccessFile_getFilePointer
  (JNIEnv *, jobject);

/*
 * Class:     java_io_RandomAccessFile
 * Method:    seek
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_java_io_RandomAccessFile_seek
  (JNIEnv *, jobject, jlong);

/*
 * Class:     java_io_RandomAccessFile
 * Method:    length
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_java_io_RandomAccessFile_length
  (JNIEnv *, jobject);

/*
 * Class:     java_io_RandomAccessFile
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_java_io_RandomAccessFile_close
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
