/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class java_io_File */

#ifndef _Included_java_io_File
#define _Included_java_io_File
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     java_io_File
 * Method:    exists0
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_java_io_File_exists0
  (JNIEnv *, jobject);

/*
 * Class:     java_io_File
 * Method:    canWrite0
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_java_io_File_canWrite0
  (JNIEnv *, jobject);

/*
 * Class:     java_io_File
 * Method:    canRead0
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_java_io_File_canRead0
  (JNIEnv *, jobject);

/*
 * Class:     java_io_File
 * Method:    isFile0
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_java_io_File_isFile0
  (JNIEnv *, jobject);

/*
 * Class:     java_io_File
 * Method:    isDirectory0
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_java_io_File_isDirectory0
  (JNIEnv *, jobject);

/*
 * Class:     java_io_File
 * Method:    lastModified0
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_java_io_File_lastModified0
  (JNIEnv *, jobject);

/*
 * Class:     java_io_File
 * Method:    length0
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_java_io_File_length0
  (JNIEnv *, jobject);

/*
 * Class:     java_io_File
 * Method:    mkdir0
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_java_io_File_mkdir0
  (JNIEnv *, jobject);

/*
 * Class:     java_io_File
 * Method:    renameTo0
 * Signature: (Ljava/io/File;)Z
 */
JNIEXPORT jboolean JNICALL Java_java_io_File_renameTo0
  (JNIEnv *, jobject, jobject);

/*
 * Class:     java_io_File
 * Method:    delete0
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_java_io_File_delete0
  (JNIEnv *, jobject);

/*
 * Class:     java_io_File
 * Method:    rmdir0
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_java_io_File_rmdir0
  (JNIEnv *, jobject);

/*
 * Class:     java_io_File
 * Method:    list0
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_java_io_File_list0
  (JNIEnv *, jobject);

/*
 * Class:     java_io_File
 * Method:    canonPath
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_java_io_File_canonPath
  (JNIEnv *, jobject, jstring);

/*
 * Class:     java_io_File
 * Method:    isAbsolute
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_java_io_File_isAbsolute
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
