/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class java_io_ObjectInputStream */

#ifndef _Included_java_io_ObjectInputStream
#define _Included_java_io_ObjectInputStream
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     java_io_ObjectInputStream
 * Method:    loadClass0
 * Signature: (Ljava/lang/Class;Ljava/lang/String;)Ljava/lang/Class;
 */
JNIEXPORT jclass JNICALL Java_java_io_ObjectInputStream_loadClass0
  (JNIEnv *, jobject, jclass, jstring);

/*
 * Class:     java_io_ObjectInputStream
 * Method:    inputClassFields
 * Signature: (Ljava/lang/Object;Ljava/lang/Class;[I)V
 */
JNIEXPORT void JNICALL Java_java_io_ObjectInputStream_inputClassFields
  (JNIEnv *, jobject, jobject, jclass, jintArray);

/*
 * Class:     java_io_ObjectInputStream
 * Method:    allocateNewObject
 * Signature: (Ljava/lang/Class;Ljava/lang/Class;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_java_io_ObjectInputStream_allocateNewObject
  (JNIEnv *, jclass, jclass, jclass);

/*
 * Class:     java_io_ObjectInputStream
 * Method:    allocateNewArray
 * Signature: (Ljava/lang/Class;I)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_java_io_ObjectInputStream_allocateNewArray
  (JNIEnv *, jclass, jclass, jint);

/*
 * Class:     java_io_ObjectInputStream
 * Method:    invokeObjectReader
 * Signature: (Ljava/lang/Object;Ljava/lang/Class;)Z
 */
JNIEXPORT jboolean JNICALL Java_java_io_ObjectInputStream_invokeObjectReader
  (JNIEnv *, jobject, jobject, jclass);

#ifdef __cplusplus
}
#endif
#endif
