/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class harpoon_Runtime_MZFExternalMap */

#ifndef _Included_harpoon_Runtime_MZFExternalMap
#define _Included_harpoon_Runtime_MZFExternalMap
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     harpoon_Runtime_MZFExternalMap
 * Method:    intGET
 * Signature: (Ljava/lang/Object;Ljava/lang/Object;I)I
 */
JNIEXPORT jint JNICALL Java_harpoon_Runtime_MZFExternalMap_intGET
  (JNIEnv *, jclass, jobject, jobject, jint);

/*
 * Class:     harpoon_Runtime_MZFExternalMap
 * Method:    intSET
 * Signature: (Ljava/lang/Object;Ljava/lang/Object;II)V
 */
JNIEXPORT void JNICALL Java_harpoon_Runtime_MZFExternalMap_intSET
  (JNIEnv *, jclass, jobject, jobject, jint, jint);

/*
 * Class:     harpoon_Runtime_MZFExternalMap
 * Method:    longGET
 * Signature: (Ljava/lang/Object;Ljava/lang/Object;J)J
 */
JNIEXPORT jlong JNICALL Java_harpoon_Runtime_MZFExternalMap_longGET
  (JNIEnv *, jclass, jobject, jobject, jlong);

/*
 * Class:     harpoon_Runtime_MZFExternalMap
 * Method:    longSET
 * Signature: (Ljava/lang/Object;Ljava/lang/Object;JJ)V
 */
JNIEXPORT void JNICALL Java_harpoon_Runtime_MZFExternalMap_longSET
  (JNIEnv *, jclass, jobject, jobject, jlong, jlong);

/*
 * Class:     harpoon_Runtime_MZFExternalMap
 * Method:    ptrGET
 * Signature: (Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_harpoon_Runtime_MZFExternalMap_ptrGET
  (JNIEnv *, jclass, jobject, jobject, jobject);

/*
 * Class:     harpoon_Runtime_MZFExternalMap
 * Method:    ptrSET
 * Signature: (Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_harpoon_Runtime_MZFExternalMap_ptrSET
  (JNIEnv *, jclass, jobject, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
