/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class harpoon_Runtime_DynamicSyncImpl */

#ifndef _Included_harpoon_Runtime_DynamicSyncImpl
#define _Included_harpoon_Runtime_DynamicSyncImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     harpoon_Runtime_DynamicSyncImpl
 * Method:    isSync
 * Signature: (Ljava/lang/Object;)Z
 */
JNIEXPORT jboolean JNICALL Java_harpoon_Runtime_DynamicSyncImpl_isSync
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
