/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class java_util_ResourceBundle */

#ifndef _Included_java_util_ResourceBundle
#define _Included_java_util_ResourceBundle
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     java_util_ResourceBundle
 * Method:    getClassContext
 * Signature: ()[Ljava/lang/Class;
 */
JNIEXPORT jobjectArray JNICALL Java_java_util_ResourceBundle_getClassContext
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
