/* DO NOT EDIT THIS FILE - it is machine generated */

#ifndef __gnu_java_awt_image_GdkPixbufDecoder__
#define __gnu_java_awt_image_GdkPixbufDecoder__

#include <jni.h>

#ifdef __cplusplus
extern "C"
{
#endif

extern void Java_gnu_java_awt_image_GdkPixbufDecoder_initState (JNIEnv *env, jclass);
extern void Java_gnu_java_awt_image_GdkPixbufDecoder_loaderWrite (JNIEnv *env, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif

#endif /* __gnu_java_awt_image_GdkPixbufDecoder__ */
