/* DO NOT EDIT THIS FILE - it is machine generated */

#ifndef __gnu_java_awt_peer_gtk_GtkPopupMenuPeer__
#define __gnu_java_awt_peer_gtk_GtkPopupMenuPeer__

#include <jni.h>

#ifdef __cplusplus
extern "C"
{
#endif

extern void Java_gnu_java_awt_peer_gtk_GtkPopupMenuPeer_setupAccelGroup (JNIEnv *env, jobject, jobject);
extern void Java_gnu_java_awt_peer_gtk_GtkPopupMenuPeer_show__IIJ (JNIEnv *env, jobject, jint, jint, jlong);

#ifdef __cplusplus
}
#endif

#endif /* __gnu_java_awt_peer_gtk_GtkPopupMenuPeer__ */
