/* DO NOT EDIT THIS FILE - it is machine generated */

#ifndef __gnu_java_nio_MappedByteFileBuffer__
#define __gnu_java_nio_MappedByteFileBuffer__

#include <jni.h>

#ifdef __cplusplus
extern "C"
{
#endif

extern jbyte Java_gnu_java_nio_MappedByteFileBuffer_nio_1read_1Byte_1file_1channel (JNIEnv *env, jclass, jobject, jint, jint, jlong);
extern void Java_gnu_java_nio_MappedByteFileBuffer_nio_1write_1Byte_1file_1channel (JNIEnv *env, jclass, jobject, jint, jint, jbyte, jlong);
extern jshort Java_gnu_java_nio_MappedByteFileBuffer_nio_1read_1Short_1file_1channel (JNIEnv *env, jclass, jobject, jint, jint, jlong);
extern void Java_gnu_java_nio_MappedByteFileBuffer_nio_1write_1Short_1file_1channel (JNIEnv *env, jclass, jobject, jint, jint, jshort, jlong);
extern jchar Java_gnu_java_nio_MappedByteFileBuffer_nio_1read_1Char_1file_1channel (JNIEnv *env, jclass, jobject, jint, jint, jlong);
extern void Java_gnu_java_nio_MappedByteFileBuffer_nio_1write_1Char_1file_1channel (JNIEnv *env, jclass, jobject, jint, jint, jchar, jlong);
extern jint Java_gnu_java_nio_MappedByteFileBuffer_nio_1read_1Int_1file_1channel (JNIEnv *env, jclass, jobject, jint, jint, jlong);
extern void Java_gnu_java_nio_MappedByteFileBuffer_nio_1write_1Int_1file_1channel (JNIEnv *env, jclass, jobject, jint, jint, jint, jlong);
extern jlong Java_gnu_java_nio_MappedByteFileBuffer_nio_1read_1Long_1file_1channel (JNIEnv *env, jclass, jobject, jint, jint, jlong);
extern void Java_gnu_java_nio_MappedByteFileBuffer_nio_1write_1Long_1file_1channel (JNIEnv *env, jclass, jobject, jint, jint, jlong, jlong);
extern jfloat Java_gnu_java_nio_MappedByteFileBuffer_nio_1read_1Float_1file_1channel (JNIEnv *env, jclass, jobject, jint, jint, jlong);
extern void Java_gnu_java_nio_MappedByteFileBuffer_nio_1write_1Float_1file_1channel (JNIEnv *env, jclass, jobject, jint, jint, jfloat, jlong);
extern jdouble Java_gnu_java_nio_MappedByteFileBuffer_nio_1read_1Double_1file_1channel (JNIEnv *env, jclass, jobject, jint, jint, jlong);
extern void Java_gnu_java_nio_MappedByteFileBuffer_nio_1write_1Double_1file_1channel (JNIEnv *env, jclass, jobject, jint, jint, jdouble, jlong);

#ifdef __cplusplus
}
#endif

#endif /* __gnu_java_nio_MappedByteFileBuffer__ */
