/* DO NOT EDIT THIS FILE - it is machine generated */

#ifndef __gnu_java_nio_ByteBufferImpl__
#define __gnu_java_nio_ByteBufferImpl__

#include <jni.h>

#ifdef __cplusplus
extern "C"
{
#endif

extern jbyteArray Java_gnu_java_nio_ByteBufferImpl_nio_1cast___3B (JNIEnv *env, jclass, jbyteArray);
extern jbyteArray Java_gnu_java_nio_ByteBufferImpl_nio_1cast___3C (JNIEnv *env, jclass, jcharArray);
extern jbyteArray Java_gnu_java_nio_ByteBufferImpl_nio_1cast___3S (JNIEnv *env, jclass, jshortArray);
extern jbyteArray Java_gnu_java_nio_ByteBufferImpl_nio_1cast___3J (JNIEnv *env, jclass, jlongArray);
extern jbyteArray Java_gnu_java_nio_ByteBufferImpl_nio_1cast___3I (JNIEnv *env, jclass, jintArray);
extern jbyteArray Java_gnu_java_nio_ByteBufferImpl_nio_1cast___3F (JNIEnv *env, jclass, jfloatArray);
extern jbyteArray Java_gnu_java_nio_ByteBufferImpl_nio_1cast___3D (JNIEnv *env, jclass, jdoubleArray);
extern jbyte Java_gnu_java_nio_ByteBufferImpl_nio_1get_1Byte (JNIEnv *env, jclass, jobject, jint, jint);
extern void Java_gnu_java_nio_ByteBufferImpl_nio_1put_1Byte (JNIEnv *env, jclass, jobject, jint, jint, jbyte);
extern jchar Java_gnu_java_nio_ByteBufferImpl_nio_1get_1Char (JNIEnv *env, jclass, jobject, jint, jint);
extern void Java_gnu_java_nio_ByteBufferImpl_nio_1put_1Char (JNIEnv *env, jclass, jobject, jint, jint, jchar);
extern jshort Java_gnu_java_nio_ByteBufferImpl_nio_1get_1Short (JNIEnv *env, jclass, jobject, jint, jint);
extern void Java_gnu_java_nio_ByteBufferImpl_nio_1put_1Short (JNIEnv *env, jclass, jobject, jint, jint, jshort);
extern jint Java_gnu_java_nio_ByteBufferImpl_nio_1get_1Int (JNIEnv *env, jclass, jobject, jint, jint);
extern void Java_gnu_java_nio_ByteBufferImpl_nio_1put_1Int (JNIEnv *env, jclass, jobject, jint, jint, jint);
extern jlong Java_gnu_java_nio_ByteBufferImpl_nio_1get_1Long (JNIEnv *env, jclass, jobject, jint, jint);
extern void Java_gnu_java_nio_ByteBufferImpl_nio_1put_1Long (JNIEnv *env, jclass, jobject, jint, jint, jlong);
extern jfloat Java_gnu_java_nio_ByteBufferImpl_nio_1get_1Float (JNIEnv *env, jclass, jobject, jint, jint);
extern void Java_gnu_java_nio_ByteBufferImpl_nio_1put_1Float (JNIEnv *env, jclass, jobject, jint, jint, jfloat);
extern jdouble Java_gnu_java_nio_ByteBufferImpl_nio_1get_1Double (JNIEnv *env, jclass, jobject, jint, jint);
extern void Java_gnu_java_nio_ByteBufferImpl_nio_1put_1Double (JNIEnv *env, jclass, jobject, jint, jint, jdouble);

#ifdef __cplusplus
}
#endif

#endif /* __gnu_java_nio_ByteBufferImpl__ */
