/* DO NOT EDIT THIS FILE - it is machine generated */

#ifndef __java_lang_VMClass__
#define __java_lang_VMClass__

#include <jni.h>

#ifdef __cplusplus
extern "C"
{
#endif

extern jboolean Java_java_lang_VMClass_isInitialized (JNIEnv *env, jobject);
extern void Java_java_lang_VMClass_setInitialized (JNIEnv *env, jobject);
extern void Java_java_lang_VMClass_step7 (JNIEnv *env, jobject);
extern void Java_java_lang_VMClass_step8 (JNIEnv *env, jobject);
extern jboolean Java_java_lang_VMClass_isInstance (JNIEnv *env, jobject, jobject);
extern jboolean Java_java_lang_VMClass_isAssignableFrom (JNIEnv *env, jobject, jclass);
extern jboolean Java_java_lang_VMClass_isInterface (JNIEnv *env, jobject);
extern jboolean Java_java_lang_VMClass_isPrimitive (JNIEnv *env, jobject);
extern jstring Java_java_lang_VMClass_getName (JNIEnv *env, jobject);
extern jclass Java_java_lang_VMClass_getSuperclass (JNIEnv *env, jobject);
extern jobjectArray Java_java_lang_VMClass_getInterfaces (JNIEnv *env, jobject);
extern jclass Java_java_lang_VMClass_getComponentType (JNIEnv *env, jobject);
extern jint Java_java_lang_VMClass_getModifiers (JNIEnv *env, jobject);
extern jclass Java_java_lang_VMClass_getDeclaringClass (JNIEnv *env, jobject);
extern jobjectArray Java_java_lang_VMClass_getDeclaredClasses (JNIEnv *env, jobject, jboolean);
extern jobjectArray Java_java_lang_VMClass_getDeclaredFields (JNIEnv *env, jobject, jboolean);
extern jobjectArray Java_java_lang_VMClass_getDeclaredMethods (JNIEnv *env, jobject, jboolean);
extern jobjectArray Java_java_lang_VMClass_getDeclaredConstructors (JNIEnv *env, jobject, jboolean);
extern jobject Java_java_lang_VMClass_getClassLoader (JNIEnv *env, jobject);
extern jclass Java_java_lang_VMClass_forName (JNIEnv *env, jclass, jstring);
extern jint Java_java_lang_VMClass_isArray (JNIEnv *env, jobject);
extern void Java_java_lang_VMClass_initialize__ (JNIEnv *env, jobject);
extern jclass Java_java_lang_VMClass_loadArrayClass (JNIEnv *env, jclass, jstring, jobject);
extern void Java_java_lang_VMClass_throwException (JNIEnv *env, jclass, jthrowable);

#ifdef __cplusplus
}
#endif

#endif /* __java_lang_VMClass__ */
