/* DO NOT EDIT THIS FILE - it is machine generated */

#ifndef __java_lang_Math__
#define __java_lang_Math__

#include <jni.h>

#ifdef __cplusplus
extern "C"
{
#endif

extern jdouble Java_java_lang_Math_sin (JNIEnv *env, jclass, jdouble);
extern jdouble Java_java_lang_Math_cos (JNIEnv *env, jclass, jdouble);
extern jdouble Java_java_lang_Math_tan (JNIEnv *env, jclass, jdouble);
extern jdouble Java_java_lang_Math_asin (JNIEnv *env, jclass, jdouble);
extern jdouble Java_java_lang_Math_acos (JNIEnv *env, jclass, jdouble);
extern jdouble Java_java_lang_Math_atan (JNIEnv *env, jclass, jdouble);
extern jdouble Java_java_lang_Math_atan2 (JNIEnv *env, jclass, jdouble, jdouble);
extern jdouble Java_java_lang_Math_exp (JNIEnv *env, jclass, jdouble);
extern jdouble Java_java_lang_Math_log (JNIEnv *env, jclass, jdouble);
extern jdouble Java_java_lang_Math_sqrt (JNIEnv *env, jclass, jdouble);
extern jdouble Java_java_lang_Math_pow (JNIEnv *env, jclass, jdouble, jdouble);
extern jdouble Java_java_lang_Math_IEEEremainder (JNIEnv *env, jclass, jdouble, jdouble);
extern jdouble Java_java_lang_Math_ceil (JNIEnv *env, jclass, jdouble);
extern jdouble Java_java_lang_Math_floor (JNIEnv *env, jclass, jdouble);
extern jdouble Java_java_lang_Math_rint (JNIEnv *env, jclass, jdouble);

#ifdef __cplusplus
}
#endif

#endif /* __java_lang_Math__ */
