/* DO NOT EDIT THIS FILE - it is machine generated */

#ifndef __java_lang_Runtime__
#define __java_lang_Runtime__

#include <jni.h>

#ifdef __cplusplus
extern "C"
{
#endif

extern jint Java_java_lang_Runtime_availableProcessors (JNIEnv *env, jobject);
extern jlong Java_java_lang_Runtime_freeMemory (JNIEnv *env, jobject);
extern jlong Java_java_lang_Runtime_totalMemory (JNIEnv *env, jobject);
extern jlong Java_java_lang_Runtime_maxMemory (JNIEnv *env, jobject);
extern void Java_java_lang_Runtime_gc (JNIEnv *env, jobject);
extern void Java_java_lang_Runtime_runFinalization (JNIEnv *env, jobject);
extern void Java_java_lang_Runtime_traceInstructions (JNIEnv *env, jobject, jboolean);
extern void Java_java_lang_Runtime_traceMethodCalls (JNIEnv *env, jobject, jboolean);
extern void Java_java_lang_Runtime_runFinalizersOnExitInternal (JNIEnv *env, jclass, jboolean);
extern void Java_java_lang_Runtime_exitInternal (JNIEnv *env, jobject, jint);
extern jint Java_java_lang_Runtime_nativeLoad (JNIEnv *env, jobject, jstring);
extern jstring Java_java_lang_Runtime_nativeGetLibname (JNIEnv *env, jclass, jstring, jstring);
extern jobject Java_java_lang_Runtime_execInternal (JNIEnv *env, jobject, jobjectArray, jobjectArray, jobject);
extern void Java_java_lang_Runtime_insertSystemProperties (JNIEnv *env, jclass, jobject);

#ifdef __cplusplus
}
#endif

#endif /* __java_lang_Runtime__ */
