/* DO NOT EDIT THIS FILE - it is machine generated */

#ifndef __java_lang_Double__
#define __java_lang_Double__

#include <jni.h>

#ifdef __cplusplus
extern "C"
{
#endif

extern jdouble Java_java_lang_Double_parseDouble (JNIEnv *env, jclass, jstring);
extern jlong Java_java_lang_Double_doubleToLongBits (JNIEnv *env, jclass, jdouble);
extern jlong Java_java_lang_Double_doubleToRawLongBits (JNIEnv *env, jclass, jdouble);
extern jdouble Java_java_lang_Double_longBitsToDouble (JNIEnv *env, jclass, jlong);
extern jstring Java_java_lang_Double_toString__DZ (JNIEnv *env, jclass, jdouble, jboolean);
extern void Java_java_lang_Double_initIDs (JNIEnv *env, jclass);

#ifdef __cplusplus
}
#endif

#endif /* __java_lang_Double__ */
