/* DO NOT EDIT THIS FILE - it is machine generated */

#ifndef __java_util_TimeZone__
#define __java_util_TimeZone__

#include <jni.h>

#ifdef __cplusplus
extern "C"
{
#endif

extern jstring Java_java_util_TimeZone_getDefaultTimeZoneId (JNIEnv *env, jclass);

#ifdef __cplusplus
}
#endif

#endif /* __java_util_TimeZone__ */
