/* DO NOT EDIT THIS FILE - it is machine generated */

#ifndef __java_lang_reflect_Field__
#define __java_lang_reflect_Field__

#include <jni.h>

#ifdef __cplusplus
extern "C"
{
#endif

extern jint Java_java_lang_reflect_Field_getModifiers (JNIEnv *env, jobject);
extern jclass Java_java_lang_reflect_Field_getType (JNIEnv *env, jobject);
extern jobject Java_java_lang_reflect_Field_get (JNIEnv *env, jobject, jobject);
extern jboolean Java_java_lang_reflect_Field_getBoolean (JNIEnv *env, jobject, jobject);
extern jbyte Java_java_lang_reflect_Field_getByte (JNIEnv *env, jobject, jobject);
extern jchar Java_java_lang_reflect_Field_getChar (JNIEnv *env, jobject, jobject);
extern jshort Java_java_lang_reflect_Field_getShort (JNIEnv *env, jobject, jobject);
extern jint Java_java_lang_reflect_Field_getInt (JNIEnv *env, jobject, jobject);
extern jlong Java_java_lang_reflect_Field_getLong (JNIEnv *env, jobject, jobject);
extern jfloat Java_java_lang_reflect_Field_getFloat (JNIEnv *env, jobject, jobject);
extern jdouble Java_java_lang_reflect_Field_getDouble (JNIEnv *env, jobject, jobject);
extern void Java_java_lang_reflect_Field_set (JNIEnv *env, jobject, jobject, jobject);
extern void Java_java_lang_reflect_Field_setBoolean (JNIEnv *env, jobject, jobject, jboolean);
extern void Java_java_lang_reflect_Field_setByte (JNIEnv *env, jobject, jobject, jbyte);
extern void Java_java_lang_reflect_Field_setChar (JNIEnv *env, jobject, jobject, jchar);
extern void Java_java_lang_reflect_Field_setShort (JNIEnv *env, jobject, jobject, jshort);
extern void Java_java_lang_reflect_Field_setInt (JNIEnv *env, jobject, jobject, jint);
extern void Java_java_lang_reflect_Field_setLong (JNIEnv *env, jobject, jobject, jlong);
extern void Java_java_lang_reflect_Field_setFloat (JNIEnv *env, jobject, jobject, jfloat);
extern void Java_java_lang_reflect_Field_setDouble (JNIEnv *env, jobject, jobject, jdouble);

#ifdef __cplusplus
}
#endif

#endif /* __java_lang_reflect_Field__ */
