/* DO NOT EDIT THIS FILE - it is machine generated */

#ifndef __java_lang_Float__
#define __java_lang_Float__

#include <jni.h>

#ifdef __cplusplus
extern "C"
{
#endif

extern jint Java_java_lang_Float_floatToIntBits (JNIEnv *env, jclass, jfloat);
extern jint Java_java_lang_Float_floatToRawIntBits (JNIEnv *env, jclass, jfloat);
extern jfloat Java_java_lang_Float_intBitsToFloat (JNIEnv *env, jclass, jint);

#ifdef __cplusplus
}
#endif

#endif /* __java_lang_Float__ */
