/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class java_lang_reflect_Constructor */

#ifndef _Included_java_lang_reflect_Constructor
#define _Included_java_lang_reflect_Constructor
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: ACCESS_PERMISSION */
/* Inaccessible static: reflectionFactory */
/* Inaccessible static: class_00024java_00024lang_00024Class */
/*
 * Class:     java_lang_reflect_Constructor
 * Method:    getModifiers
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_java_lang_reflect_Constructor_getModifiers
  (JNIEnv *, jobject);

/*
 * Class:     java_lang_reflect_Constructor
 * Method:    constructNative
 * Signature: ([Ljava/lang/Object;Ljava/lang/Class;I)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_java_lang_reflect_Constructor_constructNative
  (JNIEnv *, jobject, jobjectArray, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
