/* DO NOT EDIT THIS FILE - it is machine generated */

#ifndef __gnu_java_nio_DoubleBufferImpl__
#define __gnu_java_nio_DoubleBufferImpl__

#include <jni.h>

#ifdef __cplusplus
extern "C"
{
#endif

extern jbyte Java_gnu_java_nio_DoubleBufferImpl_nio_1get_1Byte (JNIEnv *env, jclass, jobject, jint, jint);
extern void Java_gnu_java_nio_DoubleBufferImpl_nio_1put_1Byte (JNIEnv *env, jclass, jobject, jint, jint, jbyte);
extern jdoubleArray Java_gnu_java_nio_DoubleBufferImpl_nio_1cast (JNIEnv *env, jclass, jbyteArray);

#ifdef __cplusplus
}
#endif

#endif /* __gnu_java_nio_DoubleBufferImpl__ */
