/* DO NOT EDIT THIS FILE - it is machine generated */

#ifndef __gnu_java_awt_peer_gtk_GtkWindowPeer__
#define __gnu_java_awt_peer_gtk_GtkWindowPeer__

#include <jni.h>

#ifdef __cplusplus
extern "C"
{
#endif

extern void Java_gnu_java_awt_peer_gtk_GtkWindowPeer_create__I (JNIEnv *env, jobject, jint);
extern void Java_gnu_java_awt_peer_gtk_GtkWindowPeer_connectHooks (JNIEnv *env, jobject);
extern void Java_gnu_java_awt_peer_gtk_GtkWindowPeer_toBack (JNIEnv *env, jobject);
extern void Java_gnu_java_awt_peer_gtk_GtkWindowPeer_toFront (JNIEnv *env, jobject);
extern void Java_gnu_java_awt_peer_gtk_GtkWindowPeer_setBounds (JNIEnv *env, jobject, jint, jint, jint, jint);
extern void Java_gnu_java_awt_peer_gtk_GtkWindowPeer_setResizable (JNIEnv *env, jobject, jboolean);
extern void Java_gnu_java_awt_peer_gtk_GtkWindowPeer_setVisible (JNIEnv *env, jobject, jboolean);

#ifdef __cplusplus
}
#endif

#endif /* __gnu_java_awt_peer_gtk_GtkWindowPeer__ */
