/* DO NOT EDIT THIS FILE - it is machine generated */

#ifndef __gnu_java_awt_peer_gtk_GtkTextFieldPeer__
#define __gnu_java_awt_peer_gtk_GtkTextFieldPeer__

#include <jni.h>

#ifdef __cplusplus
extern "C"
{
#endif

extern void Java_gnu_java_awt_peer_gtk_GtkTextFieldPeer_create (JNIEnv *env, jobject);
extern void Java_gnu_java_awt_peer_gtk_GtkTextFieldPeer_createHooks (JNIEnv *env, jobject);
extern void Java_gnu_java_awt_peer_gtk_GtkTextFieldPeer_gtkEntryGetSize (JNIEnv *env, jobject, jint, jintArray);
extern void Java_gnu_java_awt_peer_gtk_GtkTextFieldPeer_gtkSetFont (JNIEnv *env, jobject, jstring, jint);
extern void Java_gnu_java_awt_peer_gtk_GtkTextFieldPeer_setEchoChar (JNIEnv *env, jobject, jchar);

#ifdef __cplusplus
}
#endif

#endif /* __gnu_java_awt_peer_gtk_GtkTextFieldPeer__ */
