/* DO NOT EDIT THIS FILE - it is machine generated */

#ifndef __gnu_java_nio_FileChannelImpl__
#define __gnu_java_nio_FileChannelImpl__

#include <jni.h>

#ifdef __cplusplus
extern "C"
{
#endif

extern jlong Java_gnu_java_nio_FileChannelImpl_lengthInternal (JNIEnv *env, jobject, jint);
extern jlong Java_gnu_java_nio_FileChannelImpl_nio_1mmap_1file (JNIEnv *env, jclass, jint, jlong, jint, jint);
extern void Java_gnu_java_nio_FileChannelImpl_nio_1unmmap_1file (JNIEnv *env, jclass, jint, jlong, jint);
extern void Java_gnu_java_nio_FileChannelImpl_nio_1msync (JNIEnv *env, jclass, jint, jlong, jint);

#ifdef __cplusplus
}
#endif

#endif /* __gnu_java_nio_FileChannelImpl__ */
