/* DO NOT EDIT THIS FILE - it is machine generated */

#ifndef __gnu_java_awt_peer_gtk_GtkMenuPeer__
#define __gnu_java_awt_peer_gtk_GtkMenuPeer__

#include <jni.h>

#ifdef __cplusplus
extern "C"
{
#endif

extern void Java_gnu_java_awt_peer_gtk_GtkMenuPeer_create (JNIEnv *env, jobject, jstring);
extern void Java_gnu_java_awt_peer_gtk_GtkMenuPeer_addItem__Ljava_awt_peer_MenuItemPeer_2IZ (JNIEnv *env, jobject, jobject, jint, jboolean);
extern void Java_gnu_java_awt_peer_gtk_GtkMenuPeer_setupAccelGroup (JNIEnv *env, jobject, jobject);
extern void Java_gnu_java_awt_peer_gtk_GtkMenuPeer_delItem (JNIEnv *env, jobject, jint);

#ifdef __cplusplus
}
#endif

#endif /* __gnu_java_awt_peer_gtk_GtkMenuPeer__ */
