/* DO NOT EDIT THIS FILE - it is machine generated */

#ifndef __gnu_java_awt_peer_gtk_GtkButtonPeer__
#define __gnu_java_awt_peer_gtk_GtkButtonPeer__

#include <jni.h>

#ifdef __cplusplus
extern "C"
{
#endif

extern void Java_gnu_java_awt_peer_gtk_GtkButtonPeer_create (JNIEnv *env, jobject);
extern void Java_gnu_java_awt_peer_gtk_GtkButtonPeer_gtkSetFont (JNIEnv *env, jobject, jstring, jint);

#ifdef __cplusplus
}
#endif

#endif /* __gnu_java_awt_peer_gtk_GtkButtonPeer__ */
