/* DO NOT EDIT THIS FILE - it is machine generated */

#ifndef __gnu_java_nio_FloatBufferImpl__
#define __gnu_java_nio_FloatBufferImpl__

#include <jni.h>

#ifdef __cplusplus
extern "C"
{
#endif

extern jfloatArray Java_gnu_java_nio_FloatBufferImpl_nio_1cast (JNIEnv *env, jclass, jbyteArray);
extern jbyte Java_gnu_java_nio_FloatBufferImpl_nio_1get_1Byte (JNIEnv *env, jclass, jobject, jint, jint);
extern void Java_gnu_java_nio_FloatBufferImpl_nio_1put_1Byte (JNIEnv *env, jclass, jobject, jint, jint, jbyte);

#ifdef __cplusplus
}
#endif

#endif /* __gnu_java_nio_FloatBufferImpl__ */
