/* DO NOT EDIT THIS FILE - it is machine generated */

#ifndef __java_lang_reflect_Constructor__
#define __java_lang_reflect_Constructor__

#include <jni.h>

#ifdef __cplusplus
extern "C"
{
#endif

extern jint Java_java_lang_reflect_Constructor_getModifiers (JNIEnv *env, jobject);
extern jobject Java_java_lang_reflect_Constructor_constructNative (JNIEnv *env, jobject, jobjectArray, jclass, jint);

#ifdef __cplusplus
}
#endif

#endif /* __java_lang_reflect_Constructor__ */
