/* DO NOT EDIT THIS FILE - it is machine generated */

#ifndef __java_net_NetworkInterface__
#define __java_net_NetworkInterface__

#include <jni.h>

#ifdef __cplusplus
extern "C"
{
#endif

extern jobject Java_java_net_NetworkInterface_getRealNetworkInterfaces (JNIEnv *env, jclass);

#ifdef __cplusplus
}
#endif

#endif /* __java_net_NetworkInterface__ */
