/* DO NOT EDIT THIS FILE - it is machine generated */

#ifndef __java_lang_Object__
#define __java_lang_Object__

#include <jni.h>

#ifdef __cplusplus
extern "C"
{
#endif

extern jclass Java_java_lang_Object_getClass (JNIEnv *env, jobject);

#ifdef __cplusplus
}
#endif

#endif /* __java_lang_Object__ */
