/* DO NOT EDIT THIS FILE - it is machine generated */

#ifndef __java_lang_reflect_Proxy__
#define __java_lang_reflect_Proxy__

#include <jni.h>

#ifdef __cplusplus
extern "C"
{
#endif

extern jclass Java_java_lang_reflect_Proxy_getProxyClass0 (JNIEnv *env, jclass, jobject, jobjectArray);
extern jobject Java_java_lang_reflect_Proxy_getProxyData0 (JNIEnv *env, jclass, jobject, jobjectArray);
extern jclass Java_java_lang_reflect_Proxy_generateProxyClass0 (JNIEnv *env, jclass, jobject, jobject);

#ifdef __cplusplus
}
#endif

#endif /* __java_lang_reflect_Proxy__ */
