/* DO NOT EDIT THIS FILE - it is machine generated */

#ifndef __java_net_InetAddress__
#define __java_net_InetAddress__

#include <jni.h>

#ifdef __cplusplus
extern "C"
{
#endif

extern jstring Java_java_net_InetAddress_getLocalHostName (JNIEnv *env, jclass);
extern jbyteArray Java_java_net_InetAddress_lookupInaddrAny (JNIEnv *env, jclass);
extern jstring Java_java_net_InetAddress_getHostByAddr (JNIEnv *env, jclass, jbyteArray);
extern jbyteArray Java_java_net_InetAddress_getHostByName (JNIEnv *env, jclass, jstring);

#ifdef __cplusplus
}
#endif

#endif /* __java_net_InetAddress__ */
