/* DO NOT EDIT THIS FILE - it is machine generated */

#ifndef __java_lang_reflect_Method__
#define __java_lang_reflect_Method__

#include <jni.h>

#ifdef __cplusplus
extern "C"
{
#endif

extern jint Java_java_lang_reflect_Method_getModifiers (JNIEnv *env, jobject);
extern jclass Java_java_lang_reflect_Method_getReturnType (JNIEnv *env, jobject);
extern jobjectArray Java_java_lang_reflect_Method_getParameterTypes (JNIEnv *env, jobject);
extern jobjectArray Java_java_lang_reflect_Method_getExceptionTypes (JNIEnv *env, jobject);
extern jobject Java_java_lang_reflect_Method_invokeNative (JNIEnv *env, jobject, jobject, jobjectArray, jclass, jint);

#ifdef __cplusplus
}
#endif

#endif /* __java_lang_reflect_Method__ */
