/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Hello3 */

#ifndef _Included_Hello3
#define _Included_Hello3
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Hello3
 * Method:    hello
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_Hello3_hello
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
