//====================================================================
/**
 *  @file    imagerec.idl
 *
 *  @author  Wes Beebee <wbeebee@mit.edu>
 */
//====================================================================

#ifndef IMAGEREC_IDL
#define IMAGEREC_IDL

/**
 * @namespace imagerec
 * @brief  Interfaces for sending data through MIT's ATR.
 *
 */
module imagerec
{
  struct ImageData {
    sequence<long> rvals;
    sequence<long> gvals;
    sequence<long> bvals;
    long width;
    long height;
    unsigned long long time;
    long id;
  };

  /**
   * @interface ClientServer
   * @brief  Control client/server.
   */ 

  interface ClientServer
    {
	void process(in ImageData id);
    };
};

#endif
