//=============================================================================
/**
 *  @file    ATRManip.idl
 *
 *  $Id: ATRManip.idl,v 1.3 2003-02-06 17:14:49 wbeebee Exp $
 *
 *  @author  Craig Rodrigues <crodrigu@bbn.com>
 */
//=============================================================================

#ifndef ATRMANIP_IDL
#define ATRMANIP_IDL

#include <quo.idl>

/**
  * @namespace ATRManip
  * @brief  Interfaces for sending data to Automatic Target 
  *         Recognition (ATR) subsystem
  */
module ATRManip
{

   typedef sequence<octet>         FrameData;

   struct Frame {
       FrameData data;
   };

   struct Coordinate {
       float c1;
       float c2;
       float c3;
   };

   /**
     * @interface ATRSysCond
     * @brief Sytem condition object for ATR to send co-ordinates
     *        of identified target
     */       
   interface ATRSysCond : quo::ValueSC
   {
       /**
         * Send coordinate data
         * @param c  coordinate data
         */
       void send_coordinate(in Coordinate c); 
   };

   /**
     * @interface Processor
     * @brief Send data to ATR for processing.
     */       
   interface Processor
   {
       /// Calibration interface (not used currently )
       void calibrate(in Frame f);

       /**
         * Send data to ATR to be processed
         * @param f  Frame data
         */
       void process(in Frame f);
   };

};


#endif
