//=============================================================================
/**
 *  @file    ATRManip.idl
 *
 *  $Id: ATRManip.idl,v 1.4 2003-05-29 23:15:11 wbeebee Exp $
 *
 *  @author  Craig Rodrigues <crodrigu@bbn.com>
 */
//=============================================================================

#ifndef ATRMANIP_IDL
#define ATRMANIP_IDL

#include <quo.idl>

/**
  * @namespace ATRManip
  * @brief  Interfaces for sending data to Automatic Target 
  *         Recognition (ATR) subsystem
  */
module ATRManip
{

   struct Coordinate {
       float c1;
       float c2;
       float c3;
       unsigned long long timestamp;
   };

   /**
     * @interface ATRSysCond
     * @brief Sytem condition object for ATR to send co-ordinates
     *        of identified target
     */       
   interface ATRSysCond : quo::ValueSC
   {
       /**
         * Send coordinate data
         * @param c  coordinate data
         */
       void send_coordinate(in Coordinate c); 
   };

};


#endif
