# =====================================================================
# (c) Copyright 2001  BBNT Solutions, LLC
# =====================================================================

#----------------------------------------------------------------------------
#
#       Makefile for the QuO idl files
#
#----------------------------------------------------------------------------

all:

install:
	install -d ${RELEASE_ROOT}/usr/share/quo/idl
	install -m 644 *.idl   ${RELEASE_ROOT}/usr/share/quo/idl
	install -m 644 README  ${RELEASE_ROOT}/usr/share/quo/idl
