/*
 * =====================================================================
 * (c) Copyright 2001  BBNT Solutions, LLC
 * =====================================================================
 */

// quo.idl,v

#ifndef QUO_CORBA_IDL
#define QUO_CORBA_IDL

#ifdef HAS_SUN_IDLTOJAVA
#pragma javaPackage "com.bbn.quo.corba"
#endif /* HAS_SUN_IDLTOJAVA */

// This is a hack to get around shared corba structs
module quo_corba {
    struct Association {
	string key;
	double value;
    };

    typedef sequence<Association> AssociationSeq;

    struct SignalEvent {
	string eventType;
	AssociationSeq properties;
    };

};



#endif /* QUO_IDL */
