/*
 * =====================================================================
 * (c) Copyright 2001  BBNT Solutions, LLC
 * =====================================================================
 */


#ifndef QUO_RSS
#define QUO_RSS

module rss
{

    /* **********************
     * Scope
     * Scopes specify resource objects by attribute and 
     * used in the RSS modeling of the network */

    struct Scope {
	string kind;
	sequence<string> parameters;
    };

    typedef sequence<Scope> Scopes;

    enum data_types { number_data, string_data, boolean_data};

    typedef union data_value_union switch(data_types) {
    case number_data:
	double  d_value;              // Data value

    case string_data:
	string  s_value;

    case boolean_data:
	boolean    b_value;
    } data_value;



    typedef struct DataValueStruct {
	long long timestamp;
	long long halflife;
	double credibility;
	string units;
	string provenance;
	data_value value;
    } DataValue; 


    // RSS needs impls for these two

    interface RSSListener {
	void newValue(in DataValue value);
    };

    interface ResourceStatusService {
	boolean bindDataFormula(in RSSListener listener, 
				in Scopes path,
				in string formula);

	boolean bindDataFormulaPath(in RSSListener listener,
				    in string path);

	void unbindDataFormula(in RSSListener listener);
    };
};

#endif
