/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class java_lang_Float */

#ifndef _Included_java_lang_Float
#define _Included_java_lang_Float
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     java_lang_Float
 * Method:    floatToIntBits
 * Signature: (F)I
 */
JNIEXPORT jint JNICALL Java_java_lang_Float_floatToIntBits
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     java_lang_Float
 * Method:    intBitsToFloat
 * Signature: (I)F
 */
JNIEXPORT jfloat JNICALL Java_java_lang_Float_intBitsToFloat
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
