/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class java_lang_Object */

#ifndef _Included_java_lang_Object
#define _Included_java_lang_Object
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     java_lang_Object
 * Method:    getReadableVersion
 * Signature: (Lharpoon/Runtime/Transactions/CommitRecord;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_java_lang_Object_getReadableVersion
  (JNIEnv *, jobject, jobject);

/*
 * Class:     java_lang_Object
 * Method:    getReadWriteableVersion
 * Signature: (Lharpoon/Runtime/Transactions/CommitRecord;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_java_lang_Object_getReadWritableVersion
  (JNIEnv *, jobject, jobject);

/*
 * Class:     java_lang_Object
 * Method:    getReadCommittedVersion
 * Signature: ()Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_java_lang_Object_getReadCommittedVersion
  (JNIEnv *, jobject);

/*
 * Class:     java_lang_Object
 * Method:    getWriteCommittedVersion
 * Signature: ()Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_java_lang_Object_getWriteCommittedVersion
  (JNIEnv *, jobject);

/*
 * Class:     java_lang_Object
 * Method:    makeCommittedVersion
 * Signature: ()Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_java_lang_Object_makeCommittedVersion
  (JNIEnv *, jobject);

/*
 * Class:     java_lang_Object
 * Method:    writeFieldFlag
 * Signature: (Ljava/lang/reflect/Field;Ljava/lang/Class;)V
 */
JNIEXPORT void JNICALL Java_java_lang_Object_writeFieldFlag
  (JNIEnv *, jobject, jobject);

/*
 * Class:     java_lang_Object
 * Method:    writeArrayElementFlag
 * Signature: (ILjava/lang/Class;)V
 */
JNIEXPORT void JNICALL Java_java_lang_Object_writeArrayElementFlag
  (JNIEnv *, jobject, jint, jclass);

/*
 * Class:     java_lang_Object
 * Method:    writeFlag
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_java_lang_Object_writeFlag
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
