#!/bin/bash

# This script cvs updates the entire FLEX and then remakes everything in FLEX

# Beginning of script

echo "1" > $UPDATING_FLEX_FILE   # a "switch" indicating that the updating process has begun
echo "1" > $UPDATED_SUCCESSFULLY_FILE   # no errors thrown in the updating process up to now

./cvs-update-all > /dev/null 2>&1 || echo "0" > $UPDATED_SUCCESSFULLY_FILE   # cvs updates everything
if [ "`cat $UPDATED_SUCCESSFULLY_FILE`" == "1" ]; then   # cvs updated successfully
    ./remake-everything $@ > /dev/null 2>&1 || echo "0" > $UPDATED_SUCCESSFULLY_FILE   # remake everything
fi

echo "0" > $UPDATING_FLEX_FILE   # a "switch" indicating that the updating process finished

# End of script
