/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class java_util_concurrent_atomic_AtomicInteger */

#ifndef _Included_java_util_concurrent_atomic_AtomicInteger
#define _Included_java_util_concurrent_atomic_AtomicInteger
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     java_util_concurrent_atomic_AtomicInteger
 * Method:    compareAndSet
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_java_util_concurrent_atomic_AtomicInteger_compareAndSet
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     java_util_concurrent_atomic_AtomicInteger
 * Method:    getAndAdd
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_java_util_concurrent_atomic_AtomicInteger_getAndAdd
  (JNIEnv *, jobject, jint);

/*
 * Class:     java_util_concurrent_atomic_AtomicInteger
 * Method:    getAndSet
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_java_util_concurrent_atomic_AtomicInteger_getAndSet
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
