/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class javax_realtime_POSIXSignalHandler */

#ifndef _Included_javax_realtime_POSIXSignalHandler
#define _Included_javax_realtime_POSIXSignalHandler
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: SIGABRT */
/* Inaccessible static: SIGALRM */
/* Inaccessible static: SIGBUS */
/* Inaccessible static: SIGCANCEL */
/* Inaccessible static: SIGCHLD */
/* Inaccessible static: SIGCLD */
/* Inaccessible static: SIGCONT */
/* Inaccessible static: SIGGEMT */
/* Inaccessible static: SIGFPE */
/* Inaccessible static: SIGFREEZE */
/* Inaccessible static: SIGHUP */
/* Inaccessible static: SIGILL */
/* Inaccessible static: SIGINT */
/* Inaccessible static: SIGIO */
/* Inaccessible static: SIGIOT */
/* Inaccessible static: SIGKILL */
/* Inaccessible static: SIGLOST */
/* Inaccessible static: SIGLWP */
/* Inaccessible static: SIGPIPE */
/* Inaccessible static: SIGPOLL */
/* Inaccessible static: SIGPROF */
/* Inaccessible static: SIGPWR */
/* Inaccessible static: SIGQUIT */
/* Inaccessible static: SIGSEGV */
/* Inaccessible static: SIGSTOP */
/* Inaccessible static: SIGSYS */
/* Inaccessible static: SIGTERM */
/* Inaccessible static: SIGTHAW */
/* Inaccessible static: SIGTRAP */
/* Inaccessible static: SIGTSTP */
/* Inaccessible static: SIGTTIN */
/* Inaccessible static: SIGTTOU */
/* Inaccessible static: SIGURG */
/* Inaccessible static: SIGUSR1 */
/* Inaccessible static: SIGUSR2 */
/* Inaccessible static: SIGVTALRM */
/* Inaccessible static: SIGWAITING */
/* Inaccessible static: SIGWINCH */
/* Inaccessible static: SIGXCPU */
/* Inaccessible static: SIGXFSZ */
#undef javax_realtime_POSIXSignalHandler_MAX_SIG
#define javax_realtime_POSIXSignalHandler_MAX_SIG 50L
/* Inaccessible static: signalsHandlersList */
/*
 * Class:     javax_realtime_POSIXSignalHandler
 * Method:    setSignals
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_javax_realtime_POSIXSignalHandler_setSignals
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
