/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class javax_realtime_RealtimeThread */

#ifndef _Included_javax_realtime_RealtimeThread
#define _Included_javax_realtime_RealtimeThread
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: threadInitNumber */
/* Inaccessible static: stopThreadPermission */
#undef javax_realtime_RealtimeThread_MIN_PRIORITY
#define javax_realtime_RealtimeThread_MIN_PRIORITY 1L
#undef javax_realtime_RealtimeThread_NORM_PRIORITY
#define javax_realtime_RealtimeThread_NORM_PRIORITY 5L
#undef javax_realtime_RealtimeThread_MAX_PRIORITY
#define javax_realtime_RealtimeThread_MAX_PRIORITY 10L
/* Inaccessible static: RTJ_init_in_progress */
/* Inaccessible static: nextThreadID */
#ifdef __cplusplus
}
#endif
#endif
