/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class javax_realtime_RealtimeClock */

#ifndef _Included_javax_realtime_RealtimeClock
#define _Included_javax_realtime_RealtimeClock
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: rtc */
/*
 * Class:     javax_realtime_RealtimeClock
 * Method:    getTimeInC
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_javax_realtime_RealtimeClock_getTimeInC
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
