/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class javax_realtime_Scheduler */

#ifndef _Included_javax_realtime_Scheduler
#define _Included_javax_realtime_Scheduler
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: defaultScheduler */
/* Inaccessible static: vt */
#undef javax_realtime_Scheduler_HANDLE_MUTEX_INIT
#define javax_realtime_Scheduler_HANDLE_MUTEX_INIT 1LL
#undef javax_realtime_Scheduler_HANDLE_MUTEX_DESTROY
#define javax_realtime_Scheduler_HANDLE_MUTEX_DESTROY 2LL
#undef javax_realtime_Scheduler_HANDLE_MUTEX_TRYLOCK
#define javax_realtime_Scheduler_HANDLE_MUTEX_TRYLOCK 4LL
#undef javax_realtime_Scheduler_HANDLE_MUTEX_LOCK
#define javax_realtime_Scheduler_HANDLE_MUTEX_LOCK 8LL
#undef javax_realtime_Scheduler_HANDLE_MUTEX_UNLOCK
#define javax_realtime_Scheduler_HANDLE_MUTEX_UNLOCK 16LL
#undef javax_realtime_Scheduler_HANDLE_COND_INIT
#define javax_realtime_Scheduler_HANDLE_COND_INIT 32LL
#undef javax_realtime_Scheduler_HANDLE_COND_DESTROY
#define javax_realtime_Scheduler_HANDLE_COND_DESTROY 64LL
#undef javax_realtime_Scheduler_HANDLE_COND_BROADCAST
#define javax_realtime_Scheduler_HANDLE_COND_BROADCAST 128LL
#undef javax_realtime_Scheduler_HANDLE_COND_SIGNAL
#define javax_realtime_Scheduler_HANDLE_COND_SIGNAL 256LL
#undef javax_realtime_Scheduler_HANDLE_COND_TIMEDWAIT
#define javax_realtime_Scheduler_HANDLE_COND_TIMEDWAIT 512LL
#undef javax_realtime_Scheduler_HANDLE_COND_WAIT
#define javax_realtime_Scheduler_HANDLE_COND_WAIT 1024LL
#undef javax_realtime_Scheduler_HANDLE_ALL
#define javax_realtime_Scheduler_HANDLE_ALL 2047LL
/* Inaccessible static: handlerNames */
/* Inaccessible static: totalThreads */
/* Inaccessible static: disabledThreads */
/* Inaccessible static: class_00024javax_00024realtime_00024Scheduler */
/*
 * Class:     javax_realtime_Scheduler
 * Method:    setQuanta
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_javax_realtime_Scheduler_setQuanta
  (JNIEnv *, jobject, jlong);

/*
 * Class:     javax_realtime_Scheduler
 * Method:    setTimer
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_javax_realtime_Scheduler_setTimer
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     javax_realtime_Scheduler
 * Method:    reserveCPU
 * Signature: (JJJ)Z
 */
JNIEXPORT jboolean JNICALL Java_javax_realtime_Scheduler_reserveCPU
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     javax_realtime_Scheduler
 * Method:    reserveNET
 * Signature: (JJJJ)Z
 */
JNIEXPORT jboolean JNICALL Java_javax_realtime_Scheduler_reserveNET
  (JNIEnv *, jobject, jlong, jlong, jlong, jlong);

/*
 * Class:     javax_realtime_Scheduler
 * Method:    sleep
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_javax_realtime_Scheduler_sleep
  (JNIEnv *, jobject, jlong);

/*
 * Class:     javax_realtime_Scheduler
 * Method:    clock
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_javax_realtime_Scheduler_clock
  (JNIEnv *, jobject);

/*
 * Class:     javax_realtime_Scheduler
 * Method:    addThreadInC
 * Signature: (Ljavax/realtime/Schedulable;J)V
 */
JNIEXPORT void JNICALL Java_javax_realtime_Scheduler_addThreadInC
  (JNIEnv *, jobject, jobject, jlong);

/*
 * Class:     javax_realtime_Scheduler
 * Method:    removeThreadInC
 * Signature: (Ljavax/realtime/Schedulable;)J
 */
JNIEXPORT jlong JNICALL Java_javax_realtime_Scheduler_removeThreadInC
  (JNIEnv *, jobject, jobject);

/*
 * Class:     javax_realtime_Scheduler
 * Method:    beginAtomic
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_javax_realtime_Scheduler_beginAtomic
  (JNIEnv *, jclass);

/*
 * Class:     javax_realtime_Scheduler
 * Method:    endAtomic
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_javax_realtime_Scheduler_endAtomic
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
