#!/bin/sh

SCR_DIR=`dirname $0`
source ${SCR_DIR}/elim_common

BUILD_OUT_DIR=${CALL_DIR}/inter/${name}.inter
MAMAPS_FILE=${CALL_DIR}/inter/analyze-${name}.inter

rm -rf ${BUILD_OUT_DIR} 
mkdir ${BUILD_OUT_DIR}

echo "HARPOON_OPTIONS = "${HARPOON_OPTIONS}

java -mx128m -oss100m \
    ${HARPOON_OPTIONS} \
harpoon.Main.PAMain $PREANALYSIS_OPT \
    --ccs=$levels --wts \
    --mamaps=${MAMAPS_FILE} --ns 1 \
    --output ${BUILD_OUT_DIR} --backend precisec --inline \
    --details \
$cls

exit $?
