#!/bin/sh

SCR_DIR=`dirname $0`

source ${SCR_DIR}/elim_common

HARPOON_OPTIONS=" -mx512m -oss100m \
		  -Dharpoon.runtime=2 \
    	          -Dharpoon.alloc.strategy=bdw \
    	          -Dharpoon.target.elf=yes \
                  -Dharpoon.class.path=$stdPath:$dir"

BUILD_OUT_DIR=${CALL_DIR}/none/${name}.none

rm -rf ${BUILD_OUT_DIR} 
mkdir ${BUILD_OUT_DIR}

if[$cls = "java_cup.main"]
then
    HARPOON_OPTIONS="-r ${FLEX_DIR}/Support/locale-root-set "$HARPOON_OPTIONS
fi

echo "pwd="`pwd`
echo "HARPOON_OPTIONS="${HARPOON_OPTIONS}

java -mx128m -oss100m \
    ${HARPOON_OPTIONS} \
harpoon.Main.SAMain \
    -c $cls -bprecisec -o ${BUILD_OUT_DIR}

exit $?
