#!/bin/sh

SCR_DIR=`dirname $0`
source ${SCR_DIR}/elim_common

il=$5

BUILD_OUT_DIR=${CALL_DIR}/intra/${name}.intra.$il
MAMAPS_FILE=${CALL_DIR}/intra/analyze-${name}.intra.$il

rm -rf ${BUILD_OUT_DIR} 
mkdir ${BUILD_OUT_DIR}

echo "HARPOON_OPTIONS = "${HARPOON_OPTIONS}

java -mx128m -oss100m \
    ${HARPOON_OPTIONS} \
harpoon.Main.PAMain ${PREANALYSIS_OPT} \
    -s --ccs=$levels --wts \
    --mamaps=${MAMAPS_FILE} \
    --sa 1 --ta 1 --ns 1 \
    --inline $il \
    --output ${BUILD_OUT_DIR} --backend precisec \
$cls

#    --ns 1 \
#    --inline 2 \
#    --details \

exit $?
