#!/bin/sh

SCR_DIR=`dirname $0`
source ${SCR_DIR}/elim_common

BUILD_OUT_DIR=${CALL_DIR}/inter/${name}.inter
MAMAPS_FILE=${CALL_DIR}/inter/analyze-${name}.inter

rm -rf ${BUILD_OUT_DIR} 
mkdir ${BUILD_OUT_DIR}

echo "HARPOON_OPTIONS = "${HARPOON_OPTIONS}

java -mx128m -oss100m \
    ${HARPOON_OPTIONS} \
harpoon.Main.PAMain ${PREANALYSIS_OPT} \
    -s --ccs=$levels --wts \
    --mamaps=${MAMAPS_FILE} --wit --sa 0 --ta 0 \
    --output ${BUILD_OUT_DIR} --backend precisec \
$cls

#    --ns 1 \
#    --inline 2 --prealloc \
#    --details \

exit $?
