#!/bin/sh

SCR_DIR=`dirname $0`
source ${SCR_DIR}/elim_common

BUILD_OUT_DIR=${CALL_DIR}/intra/${name}.intra
MAMAPS_FILE=${CALL_DIR}/intra/analyze-${name}.intra

rm -rf ${BUILD_OUT_DIR} 
mkdir ${BUILD_OUT_DIR}


java -mx128m -oss100m \
    ${HARPOON_OPTIONS} \
harpoon.Main.PAMain ${PREANALYSIS_OPT} \
    -s --ccs=$levels --wts \
    --mamaps=${MAMAPS_FILE} --noit --ns 1 --inline \
    --output ${BUILD_OUT_DIR} --backend precisec \
    --details \
$cls

#   --details \
exit $?
